### ISSUE TITLE
Installation fails due to Konsole dependency

### ISSUE THREAD

**Issue by filmor** [goblinfactory/progress-bar#1]
When I try to install Goblinfactory.ProgressBar v0.3.0 it fails on trying to install `Konsole`. I think something went wrong in your package creation as the package Konsole (without the prefix) doesn't exist and you seem to have embedded it instead.

**Comment by goblinfactory** [comment]
Hi @filmor just looking at this now (lunch break).
It's not supposed to have any dependencies, let me fix that. 
sorry didn't have time to finish this during a quick break, will finish when on the train later today.

**Comment by goblinfactory** [comment]
Hi @filmor : fixed, published version `0.4.0`. Please update or install the latest nuget package.

**Comment by filmor** [comment]
Thanks, the new version works fine :)
