### ISSUE TITLE
The program exited before the progress bar was updated.

### ISSUE THREAD

**Issue by pelva** [goblinfactory/progress-bar#4]
The following code demonstrates this situation: If a 5 millisecond delay is added after pp.Report, the progress bar will be displayed normally.
```
 static  int Main(string[] args)
 {
     var pb = new ProgressBar(100);
     IProgress<int> pp = new Progress<int>(value =>
     {

         pb.Refresh(value, "Test ");
       

     });

     for (int i = 0; i <= 100; i++)
     {
         pp.Report(i);
   
     }
     Console.WriteLine("over");
     return 1;
 }
```

How to avoid this situation? In actual situations, the task has been completed, but the progress bar has not reached 100, and the program exits.

**Comment by pelva** [comment]
Sorry, this question is caused by Progress and should not be posted here

**Comment by goblinfactory** [comment]
Ah, glad it's sorted.
@pelva if you raised the issue I believe you should be able to close it? If not let me know and I'll close it.
